VERSION_YEAR = 2023
VERSION_MONTH = int('03')
VERSION_DAY = int('15')
VERSION_HOUR = int('04')
VERSION_MINUTE = int('14')
MAJOR_VERSION = 1
MINOR_VERSION = 0
PATCH_VERSION = 202303150414
version_date = '2023/03/15 04:14'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
