VERSION_YEAR = 2023
VERSION_MONTH = int('04')
VERSION_DAY = int('08')
VERSION_HOUR = int('10')
VERSION_MINUTE = int('04')
MAJOR_VERSION = 1
MINOR_VERSION = 0
PATCH_VERSION = 202304081004
version_date = '2023/04/08 10:04'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
