VERSION_YEAR = 2023
VERSION_MONTH = int('04')
VERSION_DAY = int('23')
VERSION_HOUR = int('15')
VERSION_MINUTE = int('11')
MAJOR_VERSION = 1
MINOR_VERSION = 0
PATCH_VERSION = 202304231511
version_date = '2023/04/23 15:11'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
