MAJOR_VERSION = <<<<<<< HEAD
MINOR_VERSION = 
PATCH_VERSION = 2
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version']
