data:
  from_datasets: 'CIFAR10'
  from_file: True  ##if False, then from_datasets is used
  folder: /home/username/work_dir
  train:
    path: /home/username/data/train
    batch_size: 32
    shuffle: True
    num_workers: 4
    pin_memory: True
  val:
    path: /home/username/data/val
    batch_size: 32
    shuffle: False
    num_workers: 4
    pin_memory: True
  test:
    path: /home/username/data/test
    batch_size: 32
    shuffle: False
    num_workers: 4
    pin_memory: True
transformation:
  resize:
    val : False
    args:
      size: [256, 256]
  random_crop:
    val : False
    args:
      size: [224, 224]
  random_horizontal_flip:
    val : True
    args:
      p: 0.5
  random_vertical_flip:
    val : False
    args:
       p: 0.5
  random_rotation:
    val : True
    args:
      degrees: 90
  random_grayscale:
    val : False
    args:
      p: 0.1
  random_color_jitter:
    val : True
    args:
      brightness: 0.4
      contrast: 0.4
      saturation: 0.4
      hue: 0.1
  normalize:
    val : False
    args:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
  to_tensor:
    val : True
  