##This package is for testing basic functionality of the package

name: Package Test

on: [push]

jobs:
    job-download:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Setup Python environment
              uses: actions/setup-python@v2
              with:
                python-version: '3.10' #Choose the appropriate Python version
            - name: Testing Action
              run: |
                  echo "Testing package"
            - name: Install mb_pytorch
              run: |
                  python3 -m pip install mb_pytorch
            # - name: Testing Modules         ## to be added
            #   run: |
            #       python3 -m mb_pytorch.test


            # - name: Install dependencies
            #   run: |
            #     python -m pip install --upgrade pip
            #     pip install -r requirements.txt 

            # - name: Install mb_pytorch
            #   run: |
            #     python3 -m pip install mb_pytorch